// src/index.ts — the public entry. Never import from ./debug here (spec §3.1; enforced in Task 5).
export const PACKAGE = '@kero-lab/mc-diorama';
export * from './model';
export * from './live-feed';
export * from './host';
export * from './types';
export * from './timeline';
export * from './seed';
export * from './playback';
export * from './frame';
export * from './interp';
export * from './render-clock';
export * from './prefs';
export { useReducedMotion } from './use-reduced-motion';
export * from './registry/blocks';
export * from './registry/cameras';
export * from './registry/custom-camera';
export * from './registry/entities';
export * from './registry/layers';
export * from './scene/textures';
export * from './scene/vanilla-blocks';
export * from './scene/door-motion';
export * from './scene/player-skin';
export * from './scene/player-motion';
export * from './scene/vanilla-material';
export { Diorama, hasWebGL } from './diorama';
export { Controls, formatClock, markerLeft } from './controls';
export { ShowOverlay } from './show-overlay';
export { useRunTimeline, MAX_BUFFER, type TimelineStatus, type RunTimeline } from './use-run-timeline';
export { PUBLIC_LAYERS } from './layers';
export { PARKOUR_LAYER } from './layers/parkour';
export { moveKindOf, landingValues, marginBand, targetKey, parkourMarkers, pasteMarkers, type MarginBand } from './layers/parkour/derive';
